services:
  rustdesk-api:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        COUNTRY: CN
        FRONTEND_GIT_REPO: https://github.com/bins-dev/rustdesk-api-web.git
        FRONTEND_GIT_BRANCH: main
    image: bins-dev/rustdesk-api
    container_name: rustdesk-api
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=<your_rustdesk_server_ip>:21116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=<your_rustdesk_server_ip>:21117
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://127.0.0.1:21114
      - RUSTDESK_API_RUSTDESK_KEY=<your_rustdesk_server_key>
    ports:
      - 21114:21114
    volumes:
      - ./data:/app/data #将数据库挂载出来方便备份
      - ./conf:/app/conf # config
      - ./resources:/app/resources # 静态资源
    restart: unless-stopped
